# Biprop Tutorial

## 2 - Election Objects

In this module we will take a closer look at the `Election` objects.

### Part 1 - Election Creation and Attributes

To demonstrate all functionallity, we need a larger example with more parties and regions. We therefore look at the most recent election of the _Interplanetary Space Dinosaur Federation_ (ISDF). The running parties, regions/voting districts and the votes are listed below. The ISDF's parliament has 100 seats. We use this to create the `Election` object.

In [1]:
import biprop as bp
import numpy as np

parties = ['Thrushes',
           'Blackbirds',
           'Sparrowhawks',
           'Starlings',
           'Geese',
           'Ducks',
           'Sparrows',
           'Owls',
           'Cuckoos',
           'Waxwings',
           'Sperrlinge']
regions = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupyter',
           'Saturn', 'Uranus', 'Neptune', 'Pluto']
votes = [[    8,     0,   162,   150,   300,     7,   113,   173],
         [ 1977,  3834,  2392,  5379,   675,  3305,  2626,  4700],
         [  439,  2467,  1620,  5454,  6596,    42,  8359,  3257],
         [    0,    40,   135,  1500,  1026,   458,  3536,  2321],
         [  751,  3525,  3373,  1407,  3328,  1704,  7256,  4163],
         [    1,     4,     0,     8,    10,     4,    13,     0],
         [ 1153,  1886,  3988,    13,   134,  1171,  7834,  6980],
         [  461,  6836,  1664,  6686,  5911,   401,  7010,  7036],
         [  106,   330,   420,   213,  1165,   284,   405,  1029],
         [  425,  8269,   265,  3813,  7055,  2857,  9659,  6160],
         [   50,  8250,   517,  7910,  7583,  2601,  5305, 114040000]]

e = bp.Election(votes)
print('e.party_names =', e.party_names)
print('e.region_names =', e.region_names)

e.party_names = None
e.region_names = None


To create an `Election` object, we always need at least a `votes` array. But we do not need to pass the party or region names. If we do not specify the names, the corresponding attributes are set to `None`. However, it is strongly recommended to always set party and region names. So let us do that now.

In [2]:
e.party_names = parties
e.region_names = regions

ValueError: Cannot assign name list with 9 regions to election with 8 regions.

It looks like something went wrong. We were able to assign the party name list, but not the region name list. The reason seems to be that the number of regions in the `votes` array does not match the number of names in `regions`. Upon closer inspection, this should not surprise us. Someone gave us an old region list that contains the region "Pluto", even though "Pluto" has not been a voting district since 2006! So let us sort that out and try again:

In [3]:
regions.remove('Pluto')
e.region_names = regions

Now it worked. When you try to set the `party_names` and `region_names` attributes, it is important that they have the correct length. The number of parties and regions of your election is defined by the shape of the `votes` array. You can access these numbers with the `shape`, `NoP`, and `NoR` attributes.

In [4]:
print('Shape of votes:    e.shape =', e.shape)
print('Number of parties: e.NoP =', e.NoP)
print('Number of regions: e.NoR =', e.NoR)

Shape of votes:    e.shape = (11, 8)
Number of parties: e.NoP = 11
Number of regions: e.NoR = 8


I just noticed that I misspelled the planet "Jupiter" (bad habit that happens when you spend too much time with iPython notebooks). We can change individual items in the `region_names` list as you would in any other list too.

In [5]:
print(f'Before: e.region_names[4] = {e.region_names[4]}')
e.region_names[4] = 'Jupiter'
print(f'After : e.region_names[4] = {e.region_names[4]}')

Before: e.region_names[4] = Jupyter
After : e.region_names[4] = Jupiter


Other `Election` attributes include `parties` and `regions` (which are just aliases for `party_names` and `region_names`), `total_votes` (the total number of votes in the `votes` array) and `total_seats`, which we will set to 100 now.

In [6]:
print('e.parties =', e.parties)
print('e.regions == e.region_names :', e.regions==e.region_names)
print('e.total_votes =', e.total_votes)
e.total_seats = 100
print('e.total_seats =', e.total_seats)


e.parties = ['Thrushes', 'Blackbirds', 'Sparrowhawks', 'Starlings', 'Geese', 'Ducks', 'Sparrows', 'Owls', 'Cuckoos', 'Waxwings', 'Sperrlinge']
e.regions == e.region_names : True
e.total_votes = 114262433.0
e.total_seats = 100


Something does not seem right though. There are only around 300'000 registered voters in the ISDF. However, we have over 114 million votes!. Let us inspect the `votes` array:

In [7]:
print('e.votes =')
print(e.votes)

e.votes =
[[8.0000e+00 0.0000e+00 1.6200e+02 1.5000e+02 3.0000e+02 7.0000e+00
  1.1300e+02 1.7300e+02]
 [1.9770e+03 3.8340e+03 2.3920e+03 5.3790e+03 6.7500e+02 3.3050e+03
  2.6260e+03 4.7000e+03]
 [4.3900e+02 2.4670e+03 1.6200e+03 5.4540e+03 6.5960e+03 4.2000e+01
  8.3590e+03 3.2570e+03]
 [0.0000e+00 4.0000e+01 1.3500e+02 1.5000e+03 1.0260e+03 4.5800e+02
  3.5360e+03 2.3210e+03]
 [7.5100e+02 3.5250e+03 3.3730e+03 1.4070e+03 3.3280e+03 1.7040e+03
  7.2560e+03 4.1630e+03]
 [1.0000e+00 4.0000e+00 0.0000e+00 8.0000e+00 1.0000e+01 4.0000e+00
  1.3000e+01 0.0000e+00]
 [1.1530e+03 1.8860e+03 3.9880e+03 1.3000e+01 1.3400e+02 1.1710e+03
  7.8340e+03 6.9800e+03]
 [4.6100e+02 6.8360e+03 1.6640e+03 6.6860e+03 5.9110e+03 4.0100e+02
  7.0100e+03 7.0360e+03]
 [1.0600e+02 3.3000e+02 4.2000e+02 2.1300e+02 1.1650e+03 2.8400e+02
  4.0500e+02 1.0290e+03]
 [4.2500e+02 8.2690e+03 2.6500e+02 3.8130e+03 7.0550e+03 2.8570e+03
  9.6590e+03 6.1600e+03]
 [5.0000e+01 8.2500e+03 5.1700e+02 7.9100e+03 7.5830e+03 2.6

AHA! Now I see it. Someone tried to cheat and added four additional zeros to the last entry in the array. Let us quickly revert that. Luckily, the `votes` array can still be modified.

In [8]:
e.votes[-1,-1] = 11404
print('e.total_votes =', e.total_votes)

e.total_votes = 233837.0


Now the total votes seem more reasonable. Quick sidenote: You may have noticed that the elements of the `votes` array are floats, not integers. This might sound weird at first, but there are some voting schemes in which the votes are weighted with different factors which can result in non-integer votes.

### Part 2 - Pre-Apportionment Phase

Now that we have defined our `Election` object, let me show you what we can do with it. Some methods modify the object data in an irreversible manner. Some methods only work before such an irreversible change was made, which is why we cannot call arbitrary methods in an arbitrary order. We can generally divide the `Election` object's life cycle into three distinct phases with different callable methods. We have a _pre-apportionment phase_, an _apportionment phase_ and a _post-apportionment phase_. In this section, we will look at the pre-apportionment phase and the methods that we can use in this phase.

The pre-apportionment phase is the time after we created the `Election` object and before we started the first apportionment calculation. In this phase, the number of parties and regions is not yet final and can still change (more specifically, they can decrease, but not increase). In all later phases, this is not the case anymore.

But why would you want the number of parties to decrease? Well, there are several good reasons. For example, you might have a dataset from a recent election with several parties, including party _A_ and party _B_. You have observed that both parties have a very similar program and ideology. So you start wondering: What if these two parties ran together as one? Would this improve their result? Would they get more or less seats if they ran together? To answer these questions, we need to merge two parties in the `Election` object and add together their votes. This could also be done with the raw data before the object creation, but the `Election` object has a method specificall for this task that is often easier to use. We will demonstrate this method here on our ISDF example.

First, let us take another look at the different parties in the ISDF election:

In [9]:
e.parties

['Thrushes',
 'Blackbirds',
 'Sparrowhawks',
 'Starlings',
 'Geese',
 'Ducks',
 'Sparrows',
 'Owls',
 'Cuckoos',
 'Waxwings',
 'Sperrlinge']

Did you notice something odd? One of these bird names is not an English name. "Sperrlinge" is just the German word for "sparrows". And indeed, only one sparrow party ran in the elections. However, the sparrow party primarily targets voters from the German speaking minority in the ISDF and often markets itself as Sperrlinge towards this group. During the counting, there must have been a mixup and some of the sparrows votes were counted towards the "Sparrows" party and some towards the "Sperrlinge" party. To undo this, we must merge these parties together and their votes up. The `Election` object has a method specifically for that called `merge`.

In [10]:
print('Total number of "Sparrow" votes before merger:  ', e.votes[6].sum())
print('Total number of "Sperrling" votes before merger:', e.votes[-1].sum())
print()

e.merge(party_mergers=[['Sparrows', 'Sperrlinge']])

print('Parties after merger:')
print('   ', e.parties)
print('Total number of "Sparrow" votes after merger:   ', e.votes[6].sum())

Total number of "Sparrow" votes before merger:   23159.0
Total number of "Sperrling" votes before merger: 43620.0

Parties after merger:
    ['Thrushes', 'Blackbirds', 'Sparrowhawks', 'Starlings', 'Geese', 'Ducks', 'Sparrows', 'Owls', 'Cuckoos', 'Waxwings']
Total number of "Sparrow" votes after merger:    66779.0


This worked! The "Sperrlinge" are not listed as party anymore and if we look at the number of votes we see that no vote got lost. Let me explain the `merge` method in a bit more detail. It has two keyword arguments, `party_mergers` and `region_mergers` which are used to specify which parties and regions should be merged. We have not used the `region_mergers` in our example above, but it works the same way as the `party_mergers`. Values passed to `merge` have to be lists containing lists. Every list in the list is merger that we want to complete and should contain the name of every party that will be merged. We can perform multiple mergers at once, for example through using

    party_mergers = [['Sparrows', 'Sperrlinge'], ['Ducks', 'Geese', 'Owls']]

The merged parties take on the name of the first party listed in the respective merger list. So if we wanted the merged party to have its German name, we could have used

In [11]:
e.merge(party_mergers=[['Sperrlinge', 'Sparrows']])
print(e.parties)

['Thrushes', 'Blackbirds', 'Sparrowhawks', 'Starlings', 'Geese', 'Ducks', 'Sperrlinge', 'Owls', 'Cuckoos', 'Waxwings']


Make sure that no party name shows up in more than once, as this will raise a `ValueError`. Note that your merger arrays can contain names that do not exist. This can be used to change the name of the newly merged party into an arbitrary new name:

In [12]:
e.merge(party_mergers=[['CAPTAIN Jack Sparrow', 'Sparrows', 'Sperrlinge']])
print(e.parties)

['Thrushes', 'Blackbirds', 'Sparrowhawks', 'Starlings', 'Geese', 'Ducks', 'CAPTAIN Jack Sparrow', 'Owls', 'Cuckoos', 'Waxwings']


The `Election` object also contains the `merge_parties` and `merge_regions` methods, which internally just call the `merge` method and can be used if you only need to merge one of the two. In our example, we could have used

In [13]:
e.merge_parties([['Sparrows', 'Sperrlinge', 'CAPTAIN Jack Sparrow']]) # We have to include
                        # 'CAPTAIN Jack Sparrow' as this is the current name of the party
print(e.parties)

['Thrushes', 'Blackbirds', 'Sparrowhawks', 'Starlings', 'Geese', 'Ducks', 'Sparrows', 'Owls', 'Cuckoos', 'Waxwings']


### Part 3 - Apportionment Phase

In this part we will look at the second phase, the so-called apportionment phase. In this phase, we can use apportionment methods to calculate different seat distributions. This phase automatically begins once you call the first method that performs an apportionment. Let us start this phase now by calculating the ISDF election's seat distribution according to biproportional apportionment (like in the last tutorial, we do not calculate the upper apportionment explicitly and have to pass `np.round` as argument):

In [14]:
e.biproportional_apportionment(party_seats=np.round, region_seats=np.round)

Lower apportionment converged after 3 iterations.


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 1, 2, 0, 2, 1, 2],
       [0, 1, 1, 2, 3, 0, 4, 1],
       [0, 0, 0, 1, 0, 0, 2, 1],
       [0, 1, 1, 1, 2, 1, 3, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 4, 2, 3, 4, 2, 5, 8],
       [0, 3, 1, 3, 2, 0, 3, 3],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 4, 0, 2, 3, 1, 4, 2]])

Now that we have started this phase, we cannot change the number of parties anymore through calling the `merge` method. Trying to do so will result in an `InvalidOrderError`.

In [15]:
e.merge(party_mergers=[['Sparrows', 'Sperrlinge']])

InvalidOrderError: Cannot merge parties or regions after the first distribution has been calculated or assigned.

I just noticed that we forgot to store the seat distribution in a local variable. We could recalculate it, but there is a faster way. The `Election` object has a `seats` attribute that stores the last calculated distribution.

In [16]:
seats = e.seats
print(seats)

[[0 0 0 0 0 0 0 0]
 [1 2 1 2 0 2 1 2]
 [0 1 1 2 3 0 4 1]
 [0 0 0 1 0 0 2 1]
 [0 1 1 1 2 1 3 2]
 [0 0 0 0 0 0 0 0]
 [1 4 2 3 4 2 5 8]
 [0 3 1 3 2 0 3 3]
 [0 0 0 0 1 0 0 1]
 [0 4 0 2 3 1 4 2]]


We will take a closer look at apportionment methods and how to use them in a later tutorial. For now we move on to the next phase.

### Part 4 - Post-Apportionment Phase

Now that we are done with our apportionment calculations, we can take a closer look at the calculated seats. Every row in the array corresponds to one party. Notice that there are two parties that did not receive any seats. In real elections, this very common. Sometimes, there are more parties that did not receive seats than parties that did. In such a case, we may want clean up our array and remove parties without seats. We also may want to sort the array such that parties with more seats or votes are higher up. Luckily for us, there is the `reorder` method that does this for us. Let's use it to sort the parties by the number of seats:

In [17]:
print(f'Party order before reordering: {e.parties}')
e.reorder(party_order='seats')
print(f'Party order after reordering : {e.parties}')
print(f'Seats array:\n{e.seats}')

Party order before reordering: ['Thrushes', 'Blackbirds', 'Sparrowhawks', 'Starlings', 'Geese', 'Ducks', 'Sparrows', 'Owls', 'Cuckoos', 'Waxwings']
Party order after reordering : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Blackbirds', 'Geese', 'Starlings', 'Cuckoos', 'Thrushes', 'Ducks']
Seats array:
[[1 4 2 3 4 2 5 8]
 [0 4 0 2 3 1 4 2]
 [0 3 1 3 2 0 3 3]
 [0 1 1 2 3 0 4 1]
 [1 2 1 2 0 2 1 2]
 [0 1 1 1 2 1 3 2]
 [0 0 0 1 0 0 2 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


The `reorder` method autamatically reorders the `votes` and `seats` arrays, and the names of parties and regions. As mentioned before, there are two parties without seats. To keep our data compact and tidy, we want to get rid of them. The `reorder` method has an `irr_parties` keyword exactly for that. We can pass three possible values: `None`, which is the default and does nothing to the irrelevant parties, `delte`, which deletes the irrelevant parties and their columns, and `other`, which groups the irrelevant parties together into a new "party" with the name "other". Deleting sounds tempting for our purpose, but it is not what we want. Using `delte` would also delete the irrelevant parties' votes and alter the total number of votes in the `votes` array, which we want to avoid. We therefore use the `other` keyword.

In [18]:
print(f'Parties before reordering  : {e.parties}')
print(f'Votes of Thrushes and Ducks: {e.votes.sum(axis=1)[-2:].sum()}')
e.reorder(irr_parties='other')
print(f'Parties after reordering   : {e.parties}')
print(f'Votes of "other" parties   : {e.votes.sum(axis=1)[-1]}')

Parties before reordering  : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Blackbirds', 'Geese', 'Starlings', 'Cuckoos', 'Thrushes', 'Ducks']
Votes of Thrushes and Ducks: 953.0
Parties after reordering   : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Blackbirds', 'Geese', 'Starlings', 'Cuckoos', 'other']
Votes of "other" parties   : 953.0


As we can see, the Thrushes and Ducks were grouped together and are now listed as "other" parties. We have also calculated the total votes for the Thrushes and Ducks before the reordering and the total votes for the other parties after reordering. Since these numbers are the same, we can rest assured that no vote was lost. The "other" parties are by default at the very end, even if you sort the parties alphabetically. If you want to avoid that, you can use `other_parties_at_end=False`. If you do not like the name "other", you can choose your own name for the other parties with the `other_parties_name` keyword:

In [19]:
print(f'Party order before reordering: {e.parties}')
e.reorder(party_order='alphabetical', irr_parties='other', other_parties_name='Loosers', other_parties_at_end=False)
print(f'Party order after reordering : {e.parties}')

Party order before reordering: ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Blackbirds', 'Geese', 'Starlings', 'Cuckoos', 'other']
Party order after reordering : ['Blackbirds', 'Cuckoos', 'Geese', 'Loosers', 'Owls', 'Sparrowhawks', 'Sparrows', 'Starlings', 'Waxwings']


Now "Loosers" is a bit disrespectfull, so let us change it back, sort the parties by the number of received votes and have the irrelevant parties at the end again:

In [20]:
print(f'Party order before reordering: {e.parties}')
# we do not need to set `other_parties_name='other'` and `other_parties_at_end=True`
# as these are the default values
e.reorder(party_order='votes', irr_parties='other')
print(f'Party order after reordering : {e.parties}')

Party order before reordering: ['Blackbirds', 'Cuckoos', 'Geese', 'Loosers', 'Owls', 'Sparrowhawks', 'Sparrows', 'Starlings', 'Waxwings']
Party order after reordering : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Geese', 'Blackbirds', 'Starlings', 'Cuckoos', 'other']


Calling `reorder` with `irr_parties='other'` or `irr_regions='delete'` changes the shapes of the `votes` and `seats` arrays and the meanings of rows and columns. Now they can also stand for collections of parties or regions. Since apportionment methods operate on parties and regions rather than on collections, performing another apportionment method now would not make sense. We have thus entered the _post-apportionment phase_. Calling another apportionment method will cause an `InvalidOrderError`. 

In [21]:
e.upper_apportionment(which='parties')

InvalidOrderError: Cannot perform upper apportionment after sorting out irrelevant parties and regions with `self.reorder`.

So far we only reordered the parties. However, we can also reorder the regions. Reordering regions works the same way. Let us order the regions alphabetically:

In [22]:
print(f'Region order before reordering: {e.regions}')
e.reorder(region_order='alphabetical')
print(f'Region order after reordering : {e.regions}')

Region order before reordering: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
Region order after reordering : ['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']


Actually, now that I look at it, ordering the planets alphabetically looks stupid. Let us go back to the initial order. Unless we are very lucky, we cannot return to the original order by ordering the regions by number of votes. We want a custom order. Luckily, we can pass such a custom order to the reorder function:

In [23]:
custom_order = ['Venus', 'Earth', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Earth', 'Pluto']
print(f'Region order before reordering: {e.regions}')
e.reorder(region_order=custom_order)
print(f'Region order after reordering : {e.regions}')

Region order before reordering: ['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']
Region order after reordering : ['Venus', 'Earth', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Mars', 'Mercury']


Oh no! I messed up the `custom_order` array. Mistakes like these happen when you code all night long and don't get enough caffeine. Well, on the plus side, this gives me the opportunity to explain to you how these custom orders work in detail. Regions that are mentioned in `custom_order` will show up first, in the order specified by `custom_order`. Regions not mentioned in `custom_order` show up last, in the same relative order they had before reordering. Since we forgot to include Mars and Mercury, they are at the end of the new order. Repetions of regions or regions that do not exist are ignored. That is why the Earth shows up between Venus and Jupiter and why Pluto does not show up at all. Now let us reorder properly:

In [24]:
custom_order = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
print(f'Region order before reordering: {e.regions}')
e.reorder(region_order=custom_order)
print(f'Region order after reordering : {e.regions}')

Region order before reordering: ['Venus', 'Earth', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Mars', 'Mercury']
Region order after reordering : ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


If you enjoy some good old code golfing, you can use `reorder` to simultaneously reorder the parties and regions.

In [25]:
print(f'Party order before reordering : {e.parties}')
print(f'Region order before reordering: {e.regions}')
e.reorder(party_order='alphabetical', irr_parties='other', region_order='votes')
print(f'Party order after reordering  : {e.parties}')
print(f'Region order after reordering : {e.regions}')

Party order before reordering : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Geese', 'Blackbirds', 'Starlings', 'Cuckoos', 'other']
Region order before reordering: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
Party order after reordering  : ['Blackbirds', 'Cuckoos', 'Geese', 'Owls', 'Sparrowhawks', 'Sparrows', 'Starlings', 'Waxwings', 'other']
Region order after reordering : ['Uranus', 'Neptune', 'Venus', 'Jupiter', 'Mars', 'Earth', 'Saturn', 'Mercury']


On the other hand, if you only want to change one thing at a time, you can also use the `reorder_parties` and `reorder_regions` methods, which are just aliases and internally call the `reorder` method.

In [26]:
print(f'Party order before reordering : {e.parties}')
print(f'Region order before reordering: {e.regions}')
e.reorder_parties(party_order='votes', irr_parties='other')
e.reorder_regions(region_order=custom_order)
print(f'Party order after reordering  : {e.parties}')
print(f'Region order after reordering : {e.regions}')

Party order before reordering : ['Blackbirds', 'Cuckoos', 'Geese', 'Owls', 'Sparrowhawks', 'Sparrows', 'Starlings', 'Waxwings', 'other']
Region order before reordering: ['Uranus', 'Neptune', 'Venus', 'Jupiter', 'Mars', 'Earth', 'Saturn', 'Mercury']
Party order after reordering  : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Geese', 'Blackbirds', 'Starlings', 'Cuckoos', 'other']
Region order after reordering : ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


Finally, let us take a look at the `irr_parties='delete'` option. If you insist on deleting the irrelevant parties rather than grouping them together, you can do that using this option.

In [27]:
print(f'Parties before deletion    : {e.parties}')
print(f'e.votes.sum() = {e.votes.sum()}')
print(f'Total votes before deletion: {e.total_votes}')
e.reorder(irr_parties='delete')
print(f'Parties after deletion     : {e.parties}')
print(f'e.votes.sum() = {e.votes.sum()}')
print(f'Total votes after deletion : {e.total_votes}')

Parties before deletion    : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Geese', 'Blackbirds', 'Starlings', 'Cuckoos', 'other']
e.votes.sum() = 233837.0
Total votes before deletion: 233837.0
Parties after deletion     : ['Sparrows', 'Waxwings', 'Owls', 'Sparrowhawks', 'Geese', 'Blackbirds', 'Starlings', 'Cuckoos']
e.votes.sum() = 232884.0
Total votes after deletion : 233837.0


Even though we have deleted a row in the `votes` array and therefore changed the value of `e.votes.sum()`, the `total_votes` attribute still returns the initial number of votes. This can be useful when you want to calculate the vote share of parties after deleting irrelevant parties.

This brings us to the end of the second module of the tutorial. Thank you for sticking around!